<?php

/**
 * Implementation of hook_services_resources().
 */
function document_download_services_resources() {
  $resources = array(
    'common_document' => array(
      'actions' => array(
        'listing' => array(
          'help' => t('Gets a List of Documents.'),
          'file' => array(
            'type' => 'inc',
            'module' => 'document_download',
            'name' => 'document_download.resource',
          ),
          'callback' => 'document_download_list',
          'args' => array(
            array(
              'name' => 'data',
              'type' => 'struct',
              'description' => 'document object',
              'source' => 'data',
              'optional' => TRUE,
            ),
          ),
          'access callback' => 'services_access_menu',
        ),
      ),
    ),
  );
  return $resources;
}

/**
 * Implements hook_default_services_endpoint().
 */
function document_download_default_services_endpoint() {
  $endpoint = new stdClass();
  $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $endpoint->api_version = 3;
  $endpoint->name = 'document_download';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'document_download';
  $endpoint->authentication = array();
  $endpoint->server_settings = array(
    'formatters' => array(
      'json' => TRUE,
      'bencode' => FALSE,
      'jsonp' => FALSE,
      'php' => FALSE,
      'xml' => FALSE,
    ),
    'parsers' => array(
      'application/json' => TRUE,
      'application/x-www-form-urlencoded' => TRUE,
      'application/vnd.php.serialized' => FALSE,
      'application/xml' => FALSE,
      'multipart/form-data' => FALSE,
      'text/xml' => FALSE,
    ),
  );
  $endpoint->resources = array(
    'common_document' => array(
      'actions' => array(
        'listing' => array(
          'enabled' => '1',
        ),
      ),
    ),
  );
  $endpoint->debug = 0;
  return array('document_download' => $endpoint);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function document_download_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
    );
  }
}